#!/usr/bin/env python3
import fileinput
import argparse

def main():
        parser = argparse.ArgumentParser()
        parser.add_argument("-n","--lines", default=10, help="-n --lines",type=int)
        parser.add_argument('filenames', nargs='*')
        args = parser.parse_args()
        n = args.lines
        b = args.filenames
        c = [""]*n

        for line in fileinput.input(b):
                c[fileinput.lineno() % n] = line
        for i in range(0, n):
                print(c[(fileinput.lineno()+i+1) % n], end="")


if __name__ == "__main__":
        main()
